---
# yamllint disable rule:line-length
name: View available compilers

# yamllint disable-line rule:truthy
on:
  workflow_call:
  workflow_dispatch:

concurrency:
  group: test-${{github.ref}}-${{github.event.pull_request.number || github.run_number}}
  cancel-in-progress: true

permissions: {}

jobs:
  run-bamboo:
    name: View available compilers with ccache
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-14
          - ubuntu-24.04
    runs-on: ${{ matrix.os }}
    steps:
      - name: Clone this repo
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
        with:
          persist-credentials: false
      - name: ccache
        uses: hendrikmuhs/ccache-action@5ebbd400eff9e74630f759d94ddd7b6c26299639 # v1.2
        with:
          create-symlink: true
          key: ${{ matrix.os }}
          verbose: 2
      - name: Check compilers
        run: |
          set -x
          _cleaned_path="$(echo "$PATH" | tr ':' '\n')"
          print_version() {
              if [[ -f "${1}" ]]; then
                  "${1}" --version
              fi
          }

          which -a gcc
          print_version /usr/bin/gcc
          print_version /usr/local/bin/gcc
          which -a clang
          print_version /usr/bin/clang
          print_version /usr/local/bin/clang
# yamllint enable rule:line-length
