---
# yamllint disable rule:line-length
name: view available compilers

# yamllint disable-line rule:truthy
on:
  workflow_call:
  workflow_dispatch:

concurrency:
  group: test-${{github.ref}}-${{github.event.pull_request.number || github.run_number}}
  cancel-in-progress: true

permissions: {}

jobs:
  run-bamboo:
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-14
          - ubuntu-24.04
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          persist-credentials: false
      - name: ccache
        uses: hendrikmuhs/ccache-action@a1209f81afb8c005c13b4296c32e363431bffea5 # v1.2
        with:
          create-symlink: true
          key: ${{ matrix.os }}
          verbose: 2
      - name: check compilers
        run: |
          set -x
          _cleaned_path="$(echo "$PATH" | tr ':' '\n')"
          print_version() {
              if [[ -f "${1}" ]]; then
                  "${1}" --version
              fi
          }

          which -a gcc
          print_version /usr/bin/gcc
          print_version /usr/local/bin/gcc
          which -a clang
          print_version /usr/bin/clang
          print_version /usr/local/bin/clang
# yamllint enable rule:line-length
