---
# yamllint disable rule:line-length
name: view available compilers

# yamllint disable-line rule:truthy
on:
  workflow_call:
  workflow_dispatch:

concurrency:
  group: test-${{github.ref}}-${{github.event.pull_request.number || github.run_number}}
  cancel-in-progress: true

jobs:
  run-bamboo:
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-14
          - ubuntu-24.04
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4
      - name: ccache
        uses: hendrikmuhs/ccache-action@ed74d11c0b343532753ecead8a951bb09bb34bc9 # v1.2
        with:
          create-symlink: true
          key: ${{ matrix.os }}-${{ matrix.build-type }}
          verbose: 2
      - name: check compilers
        run: |
          set -x
          _cleaned_path="$(echo "$PATH" | tr ':' '\n')"
          print_version() {
              if [[ -f "${1}" ]]; then
                  "${1}" --version
              fi
          }

          which -a gcc
          print_version /usr/bin/gcc
          print_version /usr/local/bin/gcc
          which -a clang
          print_version /usr/bin/clang
          print_version /usr/local/bin/gcc
# yamllint enable rule:line-length
